export interface AuditLogFailureData {
  failureDescription?: string;
  action: string;
  affectedObjectName: string;
  entityType?: string;
  entityId?: string;
  timestamp: string;
  errorMessage: string;
}

export function auditLogFailureTemplate(data: AuditLogFailureData) {
  const subject = `[SmartCookie] Alert: Audit Log Write Failure (${data.action})`;
  const failureDesc =
    data.failureDescription ||
    'An audit log entry could not be written to the database after retry.';
  const text = `Audit Log Write Failure Alert\n\n${failureDesc}\n\nAction: ${data.action}\nAffected Object: ${data.affectedObjectName}\nTimestamp: ${data.timestamp}\nError: ${data.errorMessage}\n\nPlease inspect system and database health.\n\nSmartCookie LMS Team`;
  const html = `
    <div style="font-family: sans-serif; padding: 20px; color: #1f2937;">
      <h2 style="color: #dc2626;">Audit Log Write Failure Alert</h2>
      <p>${failureDesc}</p>
      <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6; width: 180px;">Action:</td><td style="padding: 6px 12px; background: #ffffff;">${data.action}</td></tr>
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Affected Object:</td><td style="padding: 6px 12px; background: #ffffff;">${data.affectedObjectName}</td></tr>
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Timestamp:</td><td style="padding: 6px 12px; background: #ffffff;">${data.timestamp}</td></tr>
      </table>
      <div style="background: #fff0f0; border-left: 4px solid #ef4444; padding: 12px; margin: 16px 0; font-family: monospace; font-size: 13px; white-space: pre-wrap;">${data.errorMessage}</div>
      <p style="font-size: 13px; color: #6b7280;">This is an automated alert generated by SmartCookie audit monitoring.</p>
    </div>
  `;
  return { subject, text, html };
}
