#!/usr/bin/env bash

# deploy/06-generate-dns-guide.sh - Generates the production DNS_SETUP.md guide.
# This script extracts the real DKIM key generated by Postal from the database,
# derives its public RSA record, and compiles a comprehensive DNS setup guide.

set -eo pipefail

# Visual styling helper
echo_info() { echo -e "\e[34m[INFO]\e[0m $*"; }
echo_success() { echo -e "\e[32m[✓]\e[0m $*"; }
echo_warning() { echo -e "\e[33m[WARNING]\e[0m $*"; }
echo_error() { echo -e "\e[31m[ERROR]\e[0m $*" >&2; }

echo "===================================================="
echo "          SmartCookie DNS Configuration Guide Gen   "
echo "===================================================="

DOMAIN="$1"
if [ -z "$DOMAIN" ]; then
    echo_error "No domain name provided."
    echo "Usage: $0 <domain-name>"
    exit 1
fi

# Locate directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DNS_GUIDE_FILE="$PROJECT_ROOT/deploy/DNS_SETUP.md"

# 1. Fetch Server Public IP
echo_info "Retrieving public IP address..."
PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org || curl -s --max-time 5 https://ifconfig.me || echo "YOUR_SERVER_PUBLIC_IP")

# 2. Retrieve Postal DB Password and DKIM private key from database container
POSTAL_CONF="/opt/postal/config/postal.yml"
MARIADB_ROOT_PASS=""
DKIM_PUBLIC_KEY=""

if [ -f "$POSTAL_CONF" ]; then
    # Extract the MariaDB root password
    MARIADB_ROOT_PASS=$(sudo grep -A 5 "main_db:" "$POSTAL_CONF" | grep "password:" | head -n1 | awk '{print $2}' | tr -d '"'\'' || echo "")
fi

if [ -n "$MARIADB_ROOT_PASS" ]; then
    echo_info "Querying Postal database for DKIM keys associated with '$DOMAIN'..."
    
    # Query database for the dkim private key of the domain
    # We query the `domains` table. Under the hood, Postal schema stores domain properties there.
    PRIVATE_KEY_PEM=$(sudo docker exec -i postal-mariadb mysql -N -s -u root -p"$MARIADB_ROOT_PASS" postal -e "SELECT dkim_private_key FROM domains WHERE name='$DOMAIN' LIMIT 1;" 2>/dev/null || echo "")
    
    if [ -n "$PRIVATE_KEY_PEM" ] && [ "$PRIVATE_KEY_PEM" != "NULL" ]; then
        echo_info "DKIM private key found! Deriving public RSA key..."
        # Extract public key from private key PEM
        PUBLIC_KEY_PEM=$(echo "$PRIVATE_KEY_PEM" | openssl rsa -pubout 2>/dev/null || echo "")
        
        if [ -n "$PUBLIC_KEY_PEM" ]; then
            # Strip headers, footers, newlines, and spaces to get the raw base64 string
            DKIM_PUBLIC_KEY=$(echo "$PUBLIC_KEY_PEM" | grep -v '^-' | tr -d '\n\r ' || echo "")
            echo_success "Public DKIM record key successfully derived."
        fi
    fi
fi

if [ -z "$DKIM_PUBLIC_KEY" ]; then
    echo_warning "No DKIM key found for domain '$DOMAIN' in Postal database."
    echo "  This is normal if you haven't logged in to Postal and added '$DOMAIN' yet."
    echo "  Generating guide with a placeholder DKIM key."
    echo "  Note: You can re-run this script later to generate the guide with the actual key."
    DKIM_PUBLIC_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0_PLACEHOLDER_DKIM_KEY_GO_TO_POSTAL_WEB_UI_TO_GET_ACTUAL_VALUE"
fi

# 3. Write out DNS_SETUP.md using a clean Markdown template
echo_info "Writing customized DNS Setup Guide to $DNS_GUIDE_FILE..."

cat << EOF > "$DNS_GUIDE_FILE"
# SmartCookie LMS & Postal Mail Server - Production DNS Setup Guide

This guide lists the exact DNS records you must configure at your domain registrar (e.g. GoDaddy, Namecheap, Cloudflare, Route 53) to enable secure web traffic and fully authenticated email delivery for your domain **$DOMAIN**.

---

## 📅 Summary of Server Details
* **Root Domain:** \`$DOMAIN\`
* **Postal Admin Console:** \`http://postal.$DOMAIN\`
* **Server Public IP:** \`$PUBLIC_IP\`

---

## 🔒 Step 1: DNS Records Table (Copy-Paste)

Create the following records inside your registrar's DNS management panel:

| Record Type | Host / Name | Value / Destination | TTL | Description |
| :--- | :--- | :--- | :--- | :--- |
| **A** | \`@\` | \`$PUBLIC_IP\` | Default / 3600 | Directs root domain traffic to this VPS. |
| **A** | \`www\` | \`$PUBLIC_IP\` | Default / 3600 | Directs www subdomain traffic to this VPS. |
| **A** | \`postal\` | \`$PUBLIC_IP\` | Default / 3600 | Directs Postal admin UI traffic to this VPS. |
| **MX** | \`@\` | \`10 postal.$DOMAIN\` | 3600 (1 hour) | Configures email routing to deliver via Postal. |
| **TXT (SPF)** | \`@\` | \`v=spf1 ip4:$PUBLIC_IP a mx ~all\` | 3600 (1 hour) | Authorizes this VPS to send emails on behalf of this domain. |
| **TXT (DKIM)** | \`postal._domainkey\` | \`v=DKIM1; k=rsa; p=$DKIM_PUBLIC_KEY\` | 3600 (1 hour) | DKIM cryptographic signature public key to verify sender integrity. |
| **TXT (DMARC)**| \`_dmarc\` | \`v=DMARC1; p=none; pct=100; rua=mailto:dmarc@$DOMAIN\` | 3600 (1 hour) | DMARC security policy. Starts at "none" to monitor traffic safely first. |

---

## ⚙️ Step 2: Non-Scriptable Requirement - PTR (Reverse DNS) Record

The single most critical factor for deliverability that **cannot** be scripted at registrar-level is the **PTR (Reverse DNS)** record. A PTR record maps your public IP address back to your hostname, verifying that the mail server is genuine.

### Actions required at your VPS Provider:
1. Log in to your **VPS Provider Control Panel** (DigitalOcean, Hetzner, Linode, AWS, Vultr, etc.).
2. Locate the networking or settings panel for this specific server instance (\`$PUBLIC_IP\`).
3. Set the **Reverse DNS / PTR** record for the IP to resolve to:
   \`postal.$DOMAIN\`
4. If there is no option in the UI, submit a support ticket requesting:
   > "Please set the Reverse DNS (PTR) record of our IP $PUBLIC_IP to postal.$DOMAIN"

---

## 🚀 Step 3: Propagation Timeline & Warm-Up Schedule

### ⌛ 1. DNS Propagation
DNS records can take **2 to 24 hours** to propagate globally. You can verify propagation using online utilities:
* **A & MX Check:** [DNSChecker.org](https://dnschecker.org)
* **SPF, DKIM, DMARC Check:** [MxToolbox.com](https://mxtoolbox.com)

### 🔥 2. IP Warm-Up (Deliverability Rule)
Because this is a fresh IP address with no mailing reputation, email providers (Gmail, Yahoo, Outlook) will rate-limit or flag large bursts of emails.
* **Week 1:** Send no more than **50** system emails/invitations per day.
* **Week 2:** Increase volume to **100-150** emails per day.
* **Week 3:** Increase volume to **300** emails per day.
* Always keep bounce rates low and ensure recipients are valid.

### 🧪 3. Complete Deliverability Verification
Before launching to real users, test your setup:
1. Go to [Mail-Tester.com](https://www.mail-tester.com).
2. It will give you a temporary testing email address.
3. Trigger a system email from SmartCookie (e.g. send an administrator invitation) to that testing address.
4. Check your score on Mail-Tester. You should aim for a perfect **10/10 score**, proving SPF, DKIM, DMARC, PTR, and server headers are perfect!

---

*Document compiled dynamically on $(date -R).*
EOF

echo_success "DNS Setup Guide generated successfully at deploy/DNS_SETUP.md!"
echo "----------------------------------------------------"
echo "Check the guide contents by opening 'deploy/DNS_SETUP.md' or running:"
echo "  cat deploy/DNS_SETUP.md"
echo "===================================================="
